# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.2.21"
kord = "0.17.0"
lavakord = "9.1.5"

[libraries]
lavakord-kord = { module = "dev.schlaubi.lavakord:kord", version.ref = "lavakord" }
lavakord-plugins-lavasrc = { module = "dev.schlaubi.lavakord:lavasrc", version.ref = "lavakord" }
lavakord-plugins-sponsorblock = { module = "dev.schlaubi.lavakord:sponsorblock", version.ref = "lavakord" }
kord-core = { module = "dev.kord:kord-core", version.ref = "kord" }
kord-core-voice = { module = "dev.kord:kord-core-voice", version.ref = "kord" }
kord-voice = { module = "dev.kord:kord-voice", version.ref = "kord" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version = "0.8.2" }
slf4j = "org.slf4j:slf4j-jdk14:2.0.17"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
